@startuml

title __TEST's Class Diagram__\n

  package com.anniefraz.dissertation.test.runner.hotswap {
    package com.anniefraz.dissertation.test.runner.hotswap.test {
      class AnnaTestClass {
          + AnnaTestClass()
          + AnnaTestClass()
      }
    }
  }
  

  package com.anniefraz.dissertation.test.runner.hotswap {
    package com.anniefraz.dissertation.test.runner.hotswap.test {
      class DelegatingTestSourceFactory {
          + DelegatingTestSourceFactory()
          + getSourceFromAnnaPath()
          + getTestSourceFromAnnaPath()
      }
    }
  }
  

  package com.anniefraz.dissertation.test.runner.hotswap {
    package com.anniefraz.dissertation.test.runner.hotswap.test {
      class HotSwappingTestRunnerFactory {
          - pluginManager : PluginManager
          + HotSwappingTestRunnerFactory()
          + getJunit4TestRunner()
      }
    }
  }
  

  package com.anniefraz.dissertation.test.runner.hotswap {
    package com.anniefraz.dissertation.test.runner.hotswap.test {
      class Junit4HotSwappingTestRunner {
          - pluginManager : PluginManager
          - junit : JUnitCore
          - testSuite : TestSuite
          + Junit4HotSwappingTestRunner()
          + run()
      }
    }
  }
  

  package com.anniefraz.dissertation.test.runner.hotswap {
    package com.anniefraz.dissertation.test.runner.hotswap.test {
      interface TestRunner {
          {abstract} + run()
      }
    }
  }
  

  package com.anniefraz.dissertation.test.runner.hotswap {
    package com.anniefraz.dissertation.test.runner.hotswap.test {
      interface TestRunnerFactory {
          {abstract} + getJunit4TestRunner()
      }
    }
  }
  

  package com.anniefraz.dissertation.test.runner.hotswap {
    package com.anniefraz.dissertation.test.runner.hotswap.test {
      interface TestSource {
          {static} + wrap()
          {abstract} + getAnnaTestClasses()
      }
    }
  }
  

  package com.anniefraz.dissertation.test.runner.hotswap {
    package com.anniefraz.dissertation.test.runner.hotswap.test {
      interface TestSourceFactory {
          {abstract} + getSourceFromAnnaPath()
          {abstract} + getTestSourceFromAnnaPath()
      }
    }
  }
  

  AnnaTestClass -up-|> AnnaClass
  DelegatingTestSourceFactory -up-|> TestSourceFactory
  DelegatingTestSourceFactory o-- SourceFactory : sourceFactory
  HotSwappingTestRunnerFactory -up-|> TestRunnerFactory
  HotSwappingTestRunnerFactory o-- InMemoryJavaCompiler : inMemoryJavaCompiler
  Junit4HotSwappingTestRunner -up-|> TestRunner
  Junit4HotSwappingTestRunner o-- InMemoryJavaCompiler : inMemoryJavaCompiler


right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
