@startuml

title __TEST's Class Diagram__\n

  package  {
    class IterativeBubbleSortTest {
        - ibs : IterativeBubbleSort
        ~ setUp()
        ~ ascTest1()
        ~ ascTest2()
        ~ ascTest3()
        ~ ascTest4()
        ~ ascTest5()
        ~ ascTest6()
        ~ ascTest7()
        ~ ascTest8()
        ~ ascTest9()
        ~ ascTest10()
        ~ descTest1()
        ~ descTest2()
        ~ descTest3()
        ~ descTest4()
        ~ descTest5()
        ~ descTest6()
        ~ descTest7()
        ~ descTest8()
        ~ descTest9()
        ~ descTest10()
        ~ randTest1()
        ~ randTest2()
        ~ randTest3()
        ~ randTest4()
        ~ randTest5()
        ~ randTest6()
        ~ randTest7()
        ~ randTest8()
        ~ randTest9()
        ~ randTest10()
    }
  }
  

  package  {
    class RecursiveBubbleSortTest {
        - rbs : RecursiveBubbleSort
        ~ ascTest1()
        ~ ascTest2()
        ~ ascTest3()
        ~ ascTest4()
        ~ ascTest5()
        ~ ascTest6()
        ~ ascTest7()
        ~ ascTest8()
        ~ ascTest9()
        ~ ascTest10()
        ~ descTest1()
        ~ descTest2()
        ~ descTest3()
        ~ descTest4()
        ~ descTest5()
        ~ descTest6()
        ~ descTest7()
        ~ descTest8()
        ~ descTest9()
        ~ descTest10()
        ~ randTest1()
        ~ randTest2()
        ~ randTest3()
        ~ randTest4()
        ~ randTest5()
        ~ randTest6()
        ~ randTest7()
        ~ randTest8()
        ~ randTest9()
        ~ randTest10()
    }
  }
  



right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
