@startuml

title __APPLICATION's Class Diagram__\n

  package  {
    package com.anniefraz.dissertation.gin {
      package com.anniefraz.dissertation.gin.application {
        class ApplicationMain {
            {static} - REPS : int
            {static} - noofEditsNoRandom : int
            {static} - compileSuccess : boolean
            {static} - LOG : Logger
            {static} + main()
            {static} - compile()
            {static} - setResults()
            {static} - sendToTestRunner()
            {static} - sendToOpacitor()
        }
      }
    }
  }
  

  package  {
    package com.anniefraz.dissertation.gin {
      package com.anniefraz.dissertation.gin.application {
        class CustomClassLoader {
            {static} - INSTANCE : CustomClassLoader
            - contained : ClassLoader
            + CustomClassLoader()
            {static} + getInstance()
            + loadClass()
            # findClass()
            + setContained()
        }
      }
    }
  }
  

  package  {
    package com.anniefraz.dissertation.gin {
      package com.anniefraz.dissertation.gin.application {
        class PatchExample {
            {static} + main()
        }
      }
    }
  }
  

  package  {
    package com.anniefraz.dissertation.gin {
      package com.anniefraz.dissertation.gin.application {
        class Results {
            {static} - LOG : Logger
            - currentRep : int
            - outputFileString : String
            - time : long
            - compiledClass : Class<?>
            - file : File
            - compileSuccess : boolean
            - passed : boolean
            - opacitorMeasurement1 : double
            - opacitorMeasurement2 : double
            - opacitorResults : String
            + Results()
            + Results()
            + Results()
            + Results()
            - createFile()
            + writeToFile()
            + getCurrentRep()
            + setCurrentRep()
            + getPatch()
            + setPatch()
            + getOutputFileString()
            + setOutputFileString()
            + getTime()
            + setTime()
            + getCompiledClass()
            + setCompiledClass()
            + setCompileSuccess()
            + getCompileSuccess()
            + setPassedTests()
            + getPassed()
            + getOpacitorMeasurement1()
            + setOpacitorMeasurement1()
            + getOpacitorMeasurement2()
            + setOpacitorMeasurement2()
        }
      }
    }
  }
  

  Results o-- Patch : patch


right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
