@startuml

title __ALGORITHMS's Class Diagram__\n

  package com.anniefraz.dissertation.algorithms.GAs.main {
    package com.anniefraz.dissertation.algorithms.GAs.main.fitness {
      class FitnessEnergy {
      }
    }
  }
  

  package com.anniefraz.dissertation.algorithms.GAs.main {
    package com.anniefraz.dissertation.algorithms.GAs.main.fitness {
      interface FitnessMeasurement {
      }
    }
  }
  

  package com.anniefraz.dissertation.algorithms.GAs.main {
    package com.anniefraz.dissertation.algorithms.GAs.main.fitness {
      class FitnessUnitTests {
      }
    }
  }
  

  package com.anniefraz.dissertation.algorithms.GAs.main {
    class GA {
    }
  }
  

  package com.anniefraz.dissertation.algorithms.GAs.toy {
    class GA {
    }
  }
  

  package com.anniefraz.dissertation.algorithms.HillClimbing {
    class HillClimbing {
    }
  }
  

  package com.anniefraz.dissertation.algorithms.GAs.toy {
    class Individual {
    }
  }
  

  package com.anniefraz.dissertation.algorithms.localSearch {
    class LocalSearch {
    }
  }
  

  package com.anniefraz.dissertation.algorithms.GAs.toy {
    class Population {
    }
  }
  

  package com.anniefraz.dissertation.algorithms.randomSearch {
    class RandomSearch {
    }
  }
  

  FitnessEnergy -up-|> FitnessMeasurement
  FitnessUnitTests -up-|> FitnessMeasurement
  GA o-- Population : population
  GA o-- Individual : fittest
  GA o-- Individual : secondFittest
  HillClimbing o-- GA : ga


right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
