@startuml

title __SIMPLE's Class Diagram__\n

  package  {
    class OtherClass {
        {static} + test2()
    }
  }
  

  package  {
    class Triangle {
        {static} ~ INVALID : int
        {static} ~ SCALENE : int
        {static} ~ EQUALATERAL : int
        {static} ~ ISOCELES : int
        + Triangle()
        {static} + classifyTriangle()
        {static} - delay()
    }
  }
  

  package  {
    class Triangle {
        {static} ~ INVALID : int
        {static} ~ SCALENE : int
        {static} ~ EQUALATERAL : int
        {static} ~ ISOCELES : int
        {static} + classifyTriangle()
        {static} - delay()
    }
  }
  

  package  {
    class Triangle2 {
        {static} + classifyTriangle()
        {static} - delay()
    }
  }
  

  package  {
    enum TriangleType {
      INVALID
      SCALENE
      EQUALATERAL
      ISOCELES
    }
  }
  

  package  {
    class Triangle2Test {
        - checkClassification()
        + testInvalidTriangles()
        + testEqualateralTriangles()
        + testIsocelesTriangles()
        + testScaleneTriangles()
    }
  }
  

  package  {
    class Triangle3 {
        {static} + classifyTriangle()
        {static} - delay()
    }
  }
  

  package  {
    enum TriangleType {
      INVALID
      SCALENE
      EQUALATERAL
      ISOCELES
    }
  }
  

  package  {
    class Triangle3Test {
        - checkClassification()
        + testInvalidTriangles()
        + testEqualateralTriangles()
        + testIsocelesTriangles()
        + testScaleneTriangles()
    }
  }
  

  package  {
    class Triangle4 {
        {static} + classifyTriangle()
        {static} - delay()
    }
  }
  

  package  {
    enum TriangleType {
      INVALID
      SCALENE
      EQUALATERAL
      ISOCELES
    }
  }
  

  package  {
    class Triangle4Test {
        - checkClassification()
        + testInvalidTriangles()
        + testEqualateralTriangles()
        + testIsocelesTriangles()
        + testScaleneTriangles()
    }
  }
  

  package  {
    class Triangle5 {
        {static} ~ INVALID : int
        {static} ~ SCALENE : int
        {static} ~ EQUALATERAL : int
        {static} ~ ISOCELES : int
        {static} + classifyTriangle()
        {static} - delay()
    }
  }
  

  package  {
    class Triangle5Test {
        - checkClassification()
        + testInvalidTriangles()
        + testEqualateralTriangles()
        + testIsocelesTriangles()
        + testScaleneTriangles()
        + testNullException()
    }
  }
  

  package  {
    class TriangleTest {
        + TriangleTest()
        - checkClassification()
        + testInvalidTriangles()
        + testEqualateralTriangles()
        + testIsocelesTriangles()
        + testScaleneTriangles()
    }
  }
  

  package  {
    class TriangleTest {
        - checkClassification()
        + testInvalidTriangles()
        + testEqualateralTriangles()
        + testIsocelesTriangles()
        + testScaleneTriangles()
    }
  }
  

  Triangle2 +-down- TriangleType
  Triangle3 +-down- TriangleType
  Triangle4 +-down- TriangleType


right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
