@startuml

title __FITNESS's Class Diagram__\n

  package com.anniefraz.dissertation.algorithms.GAs.main {
    package com.anniefraz.dissertation.algorithms.GAs.main.fitness {
      class FitnessEnergy {
          {static} ~ LOG : Logger
          - testSrcDir : String
          - testBinDir : String
          - output : String
          - result : double
          + measure()
          + codeLengthOpacitor()
          + superSimpleJalenOpacitor()
          + bytecodeHistogramOpacitor()
          + getOutput()
          + setOutput()
      }
    }
  }
  

  package com.anniefraz.dissertation.algorithms.GAs.main {
    package com.anniefraz.dissertation.algorithms.GAs.main.fitness {
      interface FitnessMeasurement {
          {abstract} + measure()
      }
    }
  }

  package com.anniefraz.dissertation.algorithms.GAs.main {
    package com.anniefraz.dissertation.algorithms.GAs.main.fitness {
      class FitnessUnitTests {
          {static} ~ LOG : Logger
          {static} - PATHNAME : String
          + measure()
      }
    }
  }

  FitnessEnergy -up-|> FitnessMeasurement
  FitnessUnitTests -up-|> FitnessMeasurement
@enduml
